### ISSUE TITLE
Feature request: Specify which OSM entities should be read from the file

### ISSUE THREAD

**Issue by invisiblefunnel** [paulmach/osm#14]
Hello and thank you for this library.

In libosmium, `osmium::io::Reader` can be initialized with `osmium::osm_entities::bits` to specify which OSM entities should be parsed and passed to the handler ([docs](https://github.com/osmcode/libosmium/blob/c965256e3c2ea8fb581e588b0c34e49cedeef57d/include/osmium/io/reader.hpp#L241-L244), [example](https://github.com/osmcode/libosmium/blob/c965256e3c2ea8fb581e588b0c34e49cedeef57d/examples/osmium_filter_discussions.cpp#L56-L59)). Specifying only the entities you want to handle does significantly improve read performance in my experience with libosmium.

I believe it can be done without changing the current behavior by adding new initialization function, perhaps `osmpbf.NewWithEntities`.

I appreciate your consideration.

**Comment by paulmach** [comment]
Looking into this, it would require editing the auto generated golang protobuf code. Somewhere like [here](https://github.com/paulmach/osm/blob/0d97c07e3814fe37aa170b80433d220facaa0d3e/osmpbf/internal/osmpbf/osmformat.pb.go#L3174) to skip ahead the `msglen` bytes if not required. That is the only way I can see to completely skip the bytes in the encoded proto message and getting maximum speedup.

Libosmium does this ([example](https://github.com/osmcode/libosmium/blob/531828135ecc2598f5276ada31e16036df23085f/include/osmium/io/detail/pbf_decoder.hpp#L148)) and it's easier for them because they use protozero which has a "scan like" api verse a full marshal like golang protobuf provides. I couldn't find any such libraries for go.

I'm like 50/50 on editing the generated proto ¯\\\_(ツ)\_/¯

**Comment by invisiblefunnel** [comment]
Thanks @paulmach. I came to roughly the same conclusion in my own investigation. Closing this until someone braver than me ports protozero to Golang :).

**Comment by paulmach** [comment]
So I did this here https://github.com/paulmach/osm/pull/18 using https://github.com/paulmach/protoscan 

I added 3 fields on the on the Scanner, SkipNodes, SkipWays, SkipRelations as the API.

**Comment by invisiblefunnel** [comment]
@paulmach amazing! I'd been [tinkering](https://gist.github.com/invisiblefunnel/fea45b30ba439f53c30b0a5135b78bdc) on the same problem. Protoscan looks excellent. Many thanks for this change.

**Comment by paulmach** [comment]
added in https://github.com/paulmach/osm/pull/18

tagged v0.2 with this and the czlib change
