### ISSUE TITLE
[Feature Request] Provide timestamp to replication sequence number function

### ISSUE THREAD

**Issue by hypervtechnics** [paulmach/osm#28]
This enables us to reimplement this script in go. Your library is a great candidate to use when working with osm data.

https://github.com/openstreetmap/osm2pgsql/blob/master/scripts/osm2pgsql-replication

**Comment by paulmach** [comment]
It sounds like you're talking about this function https://github.com/osmcode/pyosmium/blob/000de57139f11cab1f22a99e7d9d3470f79f0947/src/osmium/replication/server.py#L197

It does a binary search over the state since that's updated **almost** every minute.  You could do this using this packages `replication` package. 
https://pkg.go.dev/github.com/paulmach/osm/replication#MinuteState

**Comment by paulmach** [comment]
sure, put it in the replication package and call it `MinuteStateForTimestamp`.

**Comment by paulmach** [comment]
This PR implements this functionality https://github.com/paulmach/osm/pull/38

**Comment by paulmach** [comment]
Just published https://github.com/paulmach/osm/releases/tag/v0.5.0 with this feature.
